import { Feather } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AppScreen } from '@/components/AppScreen';
import { ScreenHeader } from '@/components/ScreenHeader';
import { PageHeader } from '@/components/page-header';
import { SectionHeading } from '@/components/section-heading';
import { colors, fonts } from '@/constants/theme';
import { useItems } from '@/store/ItemsContext';
import { formatPeso } from '@/utils/money';
import { nextScheduledDate } from '@/utils/recurrence';

export default function PlanningScreen() {
  const router = useRouter();
  const { recurringRules, budgets, transactions } = useItems();
  const now = new Date();
  const monthlyExpenses = transactions.filter((item) => { const date = new Date(item.occurredAt); return item.type === 'expense' && date.getFullYear() === now.getFullYear() && date.getMonth() === now.getMonth(); });
  return <AppScreen assistant><ScreenHeader back /><PageHeader title="Plans and budgets" supporting="Inspect the rules that shape your month." action={<Pressable accessibilityRole="button" onPress={() => router.push('/life')} style={styles.editButton}><Text style={styles.editText}>Edit</Text></Pressable>} /><View style={styles.section}><SectionHeading title="Automations" detail="Salary, bills, and recurring investments" /><View style={styles.list}>{recurringRules.map((rule) => <View key={rule.id} style={styles.row}><View style={styles.icon}><Feather name={rule.kind === 'income' ? 'arrow-down-left' : rule.kind === 'investment' ? 'trending-up' : 'arrow-up-right'} size={17} color={colors.ink} /></View><View style={styles.main}><Text style={styles.title}>{rule.title}</Text><Text style={styles.meta}>{rule.days.map((day) => ordinal(day)).join(' and ')} · {formatPeso(rule.amountMinor)}</Text><Text style={styles.status}>{rule.active ? `Next ${nextScheduledDate(rule) ?? 'date unavailable'}` : 'Paused'}</Text></View></View>)}{!recurringRules.length ? <Empty text="No salary, bill, or investment automations yet." /> : null}</View></View><View style={styles.section}><SectionHeading title="Monthly budgets" /><View style={styles.list}>{budgets.map((budget) => { const used = monthlyExpenses.filter((item) => item.category.toLocaleLowerCase() === budget.category.toLocaleLowerCase()).reduce((sum, item) => sum + item.amountMinor, 0); const percent = Math.min(used / budget.limitMinor, 1); return <View key={budget.id} style={styles.budget}><View style={styles.budgetTop}><View><Text style={styles.title}>{budget.category}</Text><Text style={styles.meta}>{formatPeso(used)} of {formatPeso(budget.limitMinor)}</Text></View><Text style={styles.percent}>{Math.round(percent * 100)}%</Text></View><View style={styles.track}><View style={[styles.fill, { width: `${percent * 100}%` }]} /></View></View>; })}{!budgets.length ? <Empty text="No monthly budgets yet." /> : null}</View></View></AppScreen>;
}

function Empty({ text }: { text: string }) { return <View style={styles.empty}><Text style={styles.emptyText}>{text}</Text></View>; }
function ordinal(value: number) { const suffix = value % 10 === 1 && value !== 11 ? 'st' : value % 10 === 2 && value !== 12 ? 'nd' : value % 10 === 3 && value !== 13 ? 'rd' : 'th'; return `${value}${suffix}`; }
const styles = StyleSheet.create({ editButton: { minHeight: 44, paddingHorizontal: 8, justifyContent: 'center' }, editText: { fontFamily: fonts.bodySemiBold, fontSize: 14, color: colors.accent }, section: { marginTop: 30 }, list: { marginTop: 12, borderTopWidth: 1, borderTopColor: colors.border }, row: { minHeight: 78, flexDirection: 'row', alignItems: 'center', gap: 13, borderBottomWidth: 1, borderBottomColor: colors.border }, icon: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.border }, main: { flex: 1 }, title: { fontFamily: fonts.bodyMedium, fontSize: 14, color: colors.ink }, meta: { marginTop: 4, fontFamily: fonts.body, fontSize: 12, color: colors.secondary }, status: { marginTop: 4, fontFamily: fonts.bodyMedium, fontSize: 10, color: colors.accent }, budget: { minHeight: 82, paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: colors.border }, budgetTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, percent: { fontFamily: fonts.bodySemiBold, fontSize: 12, fontVariant: ['tabular-nums'], color: colors.ink }, track: { height: 5, marginTop: 12, borderRadius: 3, overflow: 'hidden', backgroundColor: colors.border }, fill: { height: '100%', borderRadius: 3, backgroundColor: colors.accent }, empty: { minHeight: 76, justifyContent: 'center', borderBottomWidth: 1, borderBottomColor: colors.border }, emptyText: { fontFamily: fonts.body, fontSize: 13, color: colors.secondary } });
