import { useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Pressable, Text, TextInput, View } from 'react-native';
import { useAppDialog } from '@/components/AppDialog';
import { AppScreen } from '@/components/AppScreen';
import { PixelCat } from '@/components/PixelCat';
import { ScreenHeader } from '@/components/ScreenHeader';
import { colors, fonts, themedStyles } from '@/constants/theme';
import { useItems } from '@/store/ItemsContext';
import { useTheme } from '@/store/ThemeContext';

export default function ProjectDetailScreen() {
  useTheme();
  const { showDialog } = useAppDialog();
  const { id } = useLocalSearchParams<{ id: string }>(); const { projects, projectSessions, addProjectHandoff } = useItems(); const project = projects.find((item) => item.id === id); const sessions = projectSessions.filter((item) => item.projectId === id); const [note, setNote] = useState(''); const [nextAction, setNextAction] = useState(project?.nextAction ?? ''); const [saving, setSaving] = useState(false);
  if (!project) return <AppScreen><ScreenHeader back /><Text style={styles.missing}>Project not found.</Text></AppScreen>;
  const save = async () => { if (!note.trim()) return showDialog({ title: 'Add a handoff note', message: 'Write what changed or where you stopped.', tone: 'warning' }); setSaving(true); try { await addProjectHandoff(project.id, note, nextAction); setNote(''); } catch (error) { showDialog({ title: 'Could not save handoff', message: error instanceof Error ? error.message : 'Your note was kept. Try again.', tone: 'danger' }); } finally { setSaving(false); } };
  return <AppScreen background={colors.paper}><ScreenHeader back /><View style={styles.hero}><View style={styles.copy}><Text style={styles.kicker}>RESUME WORK</Text><Text style={styles.title}>{project.name}</Text></View><PixelCat pose="sorting" size={82} speech="WELCOME BACK" /></View><View style={styles.resume}><Text style={styles.label}>CURRENT FOCUS</Text><Text style={styles.value}>{project.currentFocus || 'No handoff note saved yet.'}</Text><Text style={styles.label}>NEXT ACTION</Text><Text style={styles.next}>{project.nextAction || 'Choose the smallest useful next step.'}</Text></View><View style={styles.form}><Text style={styles.sectionTitle}>SAVE WHERE YOU STOPPED</Text><TextInput value={note} onChangeText={setNote} multiline placeholder="What changed? Where did you stop?" placeholderTextColor={colors.muted} style={[styles.input, styles.notes]} /><TextInput value={nextAction} onChangeText={setNextAction} placeholder="What should happen next?" placeholderTextColor={colors.muted} style={styles.input} /><Pressable accessibilityRole="button" accessibilityState={{ busy: saving, disabled: saving }} disabled={saving} onPress={save} style={styles.button}><Text style={styles.buttonText}>{saving ? 'SAVING...' : 'SAVE HANDOFF + 8 XP'}</Text></Pressable></View><Text style={styles.sectionTitle}>SESSION HISTORY</Text><View style={styles.history}>{sessions.map((session) => <View key={session.id} style={styles.session}><Text style={styles.sessionDate}>{new Intl.DateTimeFormat('en-PH', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(session.createdAt))}</Text><Text style={styles.sessionNote}>{session.note}</Text>{session.nextAction ? <Text style={styles.sessionNext}>NEXT: {session.nextAction}</Text> : null}</View>)}{!sessions.length ? <Text style={styles.empty}>Your saved handoffs will appear here.</Text> : null}</View></AppScreen>;
}

const styles = themedStyles(() => ({ missing: { paddingTop: 80, textAlign: 'center', fontFamily: fonts.body, color: colors.secondary }, hero: { flexDirection: 'row', alignItems: 'center' }, copy: { flex: 1 }, kicker: { fontFamily: fonts.bodySemiBold, fontSize: 11, color: colors.accent }, title: { marginTop: 6, fontFamily: fonts.bodyBold, fontSize: 31, lineHeight: 33, color: colors.ink }, resume: { marginTop: 20, paddingVertical: 18, gap: 7, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.borderStrong }, label: { marginTop: 5, fontFamily: fonts.bodySemiBold, fontSize: 10, color: colors.secondary }, value: { fontFamily: fonts.body, fontSize: 14, lineHeight: 20, color: colors.ink }, next: { fontFamily: fonts.bodySemiBold, fontSize: 15, lineHeight: 21, color: colors.ink }, form: { marginTop: 28, gap: 10 }, sectionTitle: { marginTop: 26, fontFamily: fonts.bodySemiBold, fontSize: 15, color: colors.ink }, input: { minHeight: 48, padding: 12, borderWidth: 1, borderColor: colors.borderStrong, fontFamily: fonts.body, fontSize: 14, color: colors.ink, textAlignVertical: 'top' }, notes: { minHeight: 92 }, button: { height: 52, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.ink }, buttonText: { fontFamily: fonts.bodySemiBold, fontSize: 13, color: colors.surface }, history: { marginTop: 10, borderTopWidth: 1, borderTopColor: colors.borderStrong }, session: { paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: colors.border }, sessionDate: { fontFamily: fonts.bodyMedium, fontSize: 10, color: colors.secondary }, sessionNote: { marginTop: 7, fontFamily: fonts.body, fontSize: 14, lineHeight: 20, color: colors.ink }, sessionNext: { marginTop: 7, fontFamily: fonts.bodySemiBold, fontSize: 10, color: colors.accent }, empty: { paddingVertical: 30, fontFamily: fonts.body, fontSize: 13, color: colors.secondary } }));
